from .campus_form import *
from .campus_view import *
from .user_form import *
from .course_form import *
from .course_view import *
from .report_view import *
from .report_form import *
from .type_course_form import *
from .type_course_view import *