# Generated by Django 5.0.6 on 2024-05-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mecip', '0002_campus_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='campus_name',
            field=models.CharField(max_length=254),
        ),
    ]
