# Generated by Django 5.0.6 on 2024-06-03 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mecip', '0004_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='owner',
        ),
    ]
