# Generated by Django 5.0.6 on 2024-06-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mecip', '0005_remove_curso_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='campus',
            field=models.ManyToManyField(blank=True, related_name='cursos', to='mecip.campus'),
        ),
    ]
