# Generated by Django 5.0.6 on 2024-06-03 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mecip', '0006_alter_curso_campus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='campus',
            field=models.ManyToManyField(related_name='cursos', to='mecip.campus'),
        ),
    ]
