# Generated by Django 5.0.6 on 2024-06-03 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mecip', '0008_teste'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teste',
        ),
    ]
