# Generated by Django 5.0.6 on 2024-06-26 14:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mecip', '0009_delete_teste'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('assessment', models.TextField()),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mecip.campus')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mecip.curso')),
            ],
            options={
                'unique_together': {('course', 'campus')},
            },
        ),
    ]
