# Generated by Django 5.0.6 on 2024-06-28 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mecip', '0010_relatorio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie_Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios', to='mecip.curso'),
        ),
        migrations.CreateModel(
            name='Type_Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name_course', models.CharField(max_length=250)),
                ('duration', models.CharField(max_length=2)),
                ('type_categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mecip.categorie_course')),
            ],
        ),
    ]
