# Generated by Django 5.0.6 on 2024-06-28 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mecip', '0011_categorie_course_alter_relatorio_course_type_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='name_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mecip.type_course'),
        ),
    ]
