# Generated by Django 5.0.6 on 2024-06-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mecip', '0012_alter_curso_name_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='name_course',
            field=models.CharField(max_length=250),
        ),
    ]
