# Generated by Django 5.0.6 on 2024-06-28 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mecip', '0013_alter_curso_name_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='name_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='mecip.type_course'),
        ),
    ]
