# Generated by Django 5.0.6 on 2024-06-28 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mecip', '0014_alter_curso_name_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='name_course',
            new_name='type_course',
        ),
    ]
