# Generated by Django 5.0.6 on 2024-06-28 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mecip', '0015_rename_name_course_curso_type_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='campus',
        ),
        migrations.AlterField(
            model_name='curso',
            name='type_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nome_curso', to='mecip.type_course'),
        ),
        migrations.AddField(
            model_name='curso',
            name='campus',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='mecip.campus'),
        ),
    ]
