# Generated by Django 5.0.6 on 2024-06-28 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mecip', '0016_remove_curso_campus_alter_curso_type_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='campus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='mecip.campus'),
        ),
        migrations.AlterUniqueTogether(
            name='curso',
            unique_together={('type_course', 'campus')},
        ),
    ]
