# Generated by Django 5.0.6 on 2026-03-14 14:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mecip', '0019_remove_report_current_team_report_assigned_team_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mecip.campus')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('field_type', models.CharField(choices=[('text', 'Texto'), ('textarea', 'Texto longo'), ('boolean', 'Sim/Não'), ('choice', 'Múltipla escolha')], default='text', max_length=25)),
                ('required', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('choices', models.TextField(blank=True, help_text='Separe opções com vírgula se for múltipla escolha (choice)')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='mecip.questionnaire')),
            ],
            options={
                'ordering': ['questionnaire', 'order'],
            },
        ),
        migrations.AddField(
            model_name='report',
            name='questionnaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='mecip.questionnaire'),
        ),
        migrations.CreateModel(
            name='ReportQuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mecip.question')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='mecip.report')),
            ],
            options={
                'unique_together': {('report', 'question')},
            },
        ),
    ]
