# Generated by Django 5.0.6 on 2026-04-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mecip', '0020_questionnaire_question_report_questionnaire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Em andamento', 'Em andamento'), ('Bloqueado', 'Bloqueado'), ('Pendente ajuste', 'Pendente ajuste'), ('Pendente avaliação', 'Pendente avaliação'), ('Aprovado', 'Aprovado'), ('Reprovado', 'Reprovado')], default='Pendente', max_length=50),
        ),
    ]
