# Generated by Django 5.0.6 on 2026-06-13 14:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mecip', '0021_alter_report_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Em andamento', 'Em andamento'), ('Bloqueado', 'Bloqueado'), ('Pendente ajuste', 'Pendente ajuste'), ('Pendente avaliação', 'Pendente avaliação'), ('Reprovado', 'Reprovado')], default='Pendente', max_length=50),
        ),
        migrations.CreateModel(
            name='Attachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('file', models.FileField(upload_to='question_attachments/')),
                ('description', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='mecip.question')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='QuestionAnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_value', models.CharField(max_length=250)),
                ('acceptance_criteria', models.TextField(blank=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_options', to='mecip.question')),
            ],
            options={
                'ordering': ['question', 'id'],
            },
        ),
    ]
