# Generated by Django 5.0.6 on 2026-06-13 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mecip', '0022_alter_report_status_attachments_questionansweroption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachments',
            name='question',
        ),
        migrations.AddField(
            model_name='attachments',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='mecip.reportquestionanswer'),
        ),
        migrations.AddField(
            model_name='reportquestionanswer',
            name='selected_answer_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_answers', to='mecip.questionansweroption'),
        ),
        migrations.AlterField(
            model_name='attachments',
            name='file',
            field=models.FileField(upload_to='answer_attachments/'),
        ),
    ]
