# Generated by Django 5.0.6 on 2026-06-17 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mecip', '0023_remove_attachments_question_attachments_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportquestionanswer',
            name='free_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
